### ISSUE TITLE
Add MT2

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/HHAnalysis#102]
As per HIG conveners request, adding back one neutrino at a time (0, 1, 2)

See the [original arXiv paper](https://arxiv.org/pdf/1309.6318v1.pdf) as well as the [H(bb)H(tautau) slides](https://indico.cern.ch/event/566850/contributions/2334666/attachments/1353414/2044281/hh_bbtt_2016Update.pdf#page=7)

**Comment by blinkseb** [comment]
Implementation code available here: http://arxiv.org/src/1411.4312v5/anc/lester_mt2_bisect.h
