### ISSUE TITLE
Evaluate usage of muon scale and b-jet regression

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/HHAnalysis#113]
We should see if it's worth enabling muon scale correction and b-jet regression. Also, what about systematic uncertainties on these correction? IIRC, it's not clear how to assign uncertainties on these corrections.

**Comment by OlivierBondu** [comment]
For the record:
- muon scale: we're switching on Rochester corrections for the data-driven DY estimation
- bjet regression: not using it for this Moriond round

closing this issue for this analysis round ?

**Comment by swertz** [comment]
Good for me!
