### ISSUE TITLE
Raise subleading pt cut

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/HHAnalysis#120]
In the emu category, the HLT path used at some point is `HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v*` but the current cut is 10 GeV. We need to increase the cut at some point.

**Comment by swertz** [comment]
Since we're using `HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_*` no need to raise the cut.
