### ISSUE TITLE
Re-apply HLT safe ID on electrons (+ IP cuts)?

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/HHAnalysis#136]
HWW ID was https://github.com/cp3-llbb/HHAnalysis/pull/125/files#diff-6cdb42586ea6220d1c53fa646556a54cL330

So official HLT ID plus IP cuts plus something else.

The recommended IP cuts (https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Offline_selection_criteria) are tighter than the ones used by HWW and have been shown to have no effect on Scale Factors. We can add them just for peace of mind, probably won't change anything.

I can put the ID+cuts back but nothing prevents us from requesting them in the plotter/skimmer at a later stage, on top of medium ID. It's just a bit more code to compile but means more freedom to go back if something has to be changed... 

Thoughts?

**Comment by OlivierBondu** [comment]
this can be closed right ?

**Comment by swertz** [comment]
Yep by #138 !
