### ISSUE TITLE
Keep explicitly the number of primary vertices in the output

### ISSUE THREAD

**Issue by BrieucF** [cp3-llbb/HHAnalysis#14]

**Comment by OlivierBondu** [comment]
`vertex_isValid().size()` should already do the job, @blinkseb can you confirm ?

**Comment by blinkseb** [comment]
`vertex_isValid().size()` returns the number of primary vertices, not the number of **valid** primary vertices. If you want the number of valid vertices, you have to iterate over the isValid array, which IIRC is a vector of bool.

**Comment by OlivierBondu** [comment]
which is, as far as I know, to study PU dependence, so it should be doing the job
