### ISSUE TITLE
Revisit the definition of leptons

### ISSUE THREAD

**Issue by BrieucF** [cp3-llbb/HHAnalysis#18]
- [x] Add loose lepton, medium lepton (for electrons), tight lepton collections, ... Rather then adding plenty of new branch in the nTuple, we could keep simply the index pointing to the collection from the central framework, keeping the info if it is an electron or a muon.
- [x] It could also be good to keep for each new collection the number of object we have in the event (nLooseLep, etc.). NB : the category definition has to be synchronized with the lepton collection we plan to use, we could maybe base it on loose leptons to begin with (so that we do not kill too many events).
- [x] Add also different isolation levels

**Comment by OlivierBondu** [comment]
@blinkseb : to address the second point, is there a way around with the structs stored from PR #22 ? Or do we need to store these manually ?

we can request `hh_leptons.isID_L`, or check `@hh_leptons.size()`, but I could not find a way to get `@hh_leptons.isID_L.size()`

**Comment by blinkseb** [comment]
A shot in the dark here. Does `hh_leptons.@isID_L.size()` work ?

**Comment by OlivierBondu** [comment]
It does :smile: !

**Comment by blinkseb** [comment]
\o/

2015-10-09 9:27 GMT+02:00 Olivier notifications@github.com:

> It does [image: :smile:] !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cp3-llbb/HHAnalysis/issues/18#issuecomment-146778588.

## 

Sébastien Brochet

**Comment by swertz** [comment]
So, you have a vector of structures, and this gives you the length of the vector which have isID_L to true?

**Comment by OlivierBondu** [comment]
yep, aka nLeptonLoose in this case

**Comment by blinkseb** [comment]
I don't think it's true. `hh_leptons.@isID_L.size()` should returns the size of the `isID_L` vector, what ever it's inside.

**Comment by OlivierBondu** [comment]
correct, did not look correctly at the content, yes, `hh_leptons.@isID_L.size()` works, but return the same as `hh_leptons.isID_L`:
- if we want to loop over the content of the trees, all the info is here
- but we don't have access to this info easily for Draw

so we need to store these multiplicities independently. Is my understanding correct ?

**Comment by blinkseb** [comment]
Ok that's weird here, I'll do some test, but my understanding so far was:
- `hh_leptons.@isID_L.size()` returns the number of entries inside the `isID_L` array
- `hh_leptons.isID_L` returns the **content** of the array, so since it's bool, only true or false for each entry.

If you need to access the number of entries with `hh_leptons.isID_L == true` I don't think there's an easy way to do that in ROOT at Draw time, but maybe there's. Time to restudy the doc :fearful:

**Comment by OlivierBondu** [comment]
after discussing with @swertz : maybe the easiest and cleanest way would be, in addition to storing `hh_leptons.isID_L`, to store another vector `hh_leptons_L`, containing the indices of the loose leptons.

This way we would both have an easy access to multiplicities, and an easy looping access over loose leptons only
(not the most optimal for the size, but not the worst either)
