### ISSUE TITLE
Definition of categories for ME weights

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/HHAnalysis#3]
separation in e+e-, mu+mu-, mu+e-, e-mu+, regardless of the pt?

**Comment by OlivierBondu** [comment]
@BrieucF : instead of the overhead of adding more categories, would just adding a bool `isPM` or `isMP` to the various candidates be enough ?

this would avoid duplicating the work to get the data/mc correction factors, which is flavour-pt category-based at the moment ?

**Comment by BrieucF** [comment]
Yes, this can do the trick. Crossing this info with isElMu, isMuEl, etc.,  gives what we need. Actually the information was already accessible via the "lepton.charge" but this is more convenient and cheap. :+1:

**Comment by OlivierBondu** [comment]
ok, thanks !
