### ISSUE TITLE
Extra cut after mapping

### ISSUE THREAD

**Issue by BrieucF** [cp3-llbb/HHAnalysis#50]
There is a problem if one wants to plot only one element per event (say llmetjj[myIndxs][0]) with an extra cut w.r.t. the map cuts. Maybe llmetjj[myIndxs][1] passed the extra cut.

**Comment by OlivierBondu** [comment]
what did you have in mind as extra cut ?

**Comment by BrieucF** [comment]
Asking for the jet ID tight for instance. This one could be added in the maps but you can think of a raised jet pt cut, cut on DRjj etc...
